Source/Web Menu/Models/ErrorViewModel.cs
namespace Bot_Menu.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Source/Web Menu/Models/PlayerInfoViewModel.cs
using System.Reflection;

namespace Bot_Menu.Models
{
    public class PlayerInfoViewModel
    {
        public int Hp=0;
        public int MaxHp = 0;
        public int Mp = 0;
        public int MaxMp = 0;
        public float X = 0;
        public float Y = 0;
        public float Z = 0;
        public short BuffCount = 0;
        public string Name;

        public string getPrecMP()
        {
            return $"{((float)Mp) * 100.0f / ((float)MaxMp)}".Replace(",",".");
        }
        public string getPrecHP()
        {
            return $"{((float)Hp) * 100.0f / ((float)MaxHp)}".Replace(",", ".");
        }
    }
}

Source/Web Menu/Controllers/HomeController.cs
using Bot_Menu.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Newtonsoft.Json;
using CodeInject.WebServ.Models;
using Microsoft.AspNetCore.SignalR;
using WebSocketSharp;

namespace Bot_Menu.Controllers
{

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;


        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        public IActionResult IndexAsync()
        {
            return View();
        }

        [HttpGet]
        public IActionResult UserInformation(string characterDataJson)
        {
            return PartialView(JsonConvert.DeserializeObject<PlayerInfoModel>(characterDataJson));
        }

        [HttpGet]
        public IActionResult AutoPotion()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAutoPotionSettings(string json)
        {
            AutoPotionSettingsModel potSettings= JsonConvert.DeserializeObject<AutoPotionSettingsModel>(json);
            return PartialView(potSettings);
        }

        [HttpPost]
        public IActionResult SetAutoPotionSettings(int procHelath, int hpItemIndex,int hpItemDurr, int procMana,int mpItemIndex, int mpItemDurr)
        {
            WebSocketSharp.WebSocket setPotions = new WebSocketSharp.WebSocket("ws://localhost:8080/AutoPotion");

            setPotions.Send(JsonConvert.SerializeObject(new
            {
                OpCode = "SetPotions",
                procHelath = procHelath,
                hpItemIndex = hpItemIndex,
                hpItemDurr = hpItemDurr,
                procMana = procMana,
                mpItemIndex = mpItemIndex,
                mpItemDurr = mpItemDurr
            }));


            return null;
        }

        [HttpGet]
        public IActionResult NpcList(string npcDataJson)
        {
            return PartialView(JsonConvert.DeserializeObject<List<CodeInject.WebServ.Models.NPCModel>>(npcDataJson));
        }

        public class SelectedValuesModel
        {
            public List<string> SelectedValues { get; set; }
        }



        public IActionResult Privacy()
        {
            return View();
        }


        public IActionResult SimpleFilter()
        {
            return View();
        }

        public IActionResult PickupFilter()
        {

            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Source/Web Menu/Controllers/PickupController.cs
using CodeInject.WebServ.Models.PickUpFilter;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Runtime.CompilerServices;

namespace Bot_Menu.Controllers
{
    public class PickupController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SimpleFilter([FromBody]string filter)
        {
            SimpleFilterModel model = JsonConvert.DeserializeObject<SimpleFilterModel>(filter);
            return PartialView(JsonConvert.DeserializeObject<SimpleFilterModel>(filter));
        }
    }
}

Source/Web Menu/Controllers/SkillController.cs
using CodeInject.WebServ.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Bot_Menu.Controllers
{
    public class SkillController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SkillConfirm([FromBody] List<int> selectedValues)
        {
       
            SetSkillsModel SkillsToSet = new SetSkillsModel()
            {
                setSkills = selectedValues
            };

            WebSocketSharp.WebSocket setSkillSocket = new WebSocketSharp.WebSocket("ws://localhost:2458/SkillList");
           
            setSkillSocket.OnOpen += (sender, e) =>
            {
                string json = JsonConvert.SerializeObject(SkillsToSet);
                setSkillSocket.Send(json);
            };

            setSkillSocket.Connect();

            return View();
        }

        [HttpPost]
        public IActionResult SkillList([FromBody] string data)
        {
            PlayerSkillModel skillListModel = JsonConvert.DeserializeObject<PlayerSkillModel>(data);

            return PartialView(skillListModel);
        }

        [HttpGet]
        public IActionResult SkillList()
        {
            return View();
        }
    }
}

Source/Web Menu/Views/Home/AutoPotion.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@



<h3>AutoPotion:</h3>


<div id="Autopotion">

</div>



<script>
    const socket = new WebSocket('ws://localhost:2458/AutoPotion');


    socket.addEventListener('open', (event) => {
        console.log('Połączenie WebSocket zostało nawiązane.');
        socket.send("Connected");
    });

    socket.addEventListener('message', (event) => {
        // Przykład: Wysłanie danych JSON do kontrolera za pomocą fetch
        fetch('/Home/GetAutoPotionSettings?json=' + event.data, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json'
            }
        })
            .then(response => {
                if (response.ok) {
                    return response.text();
                } else {
                    throw new Error('Błąd podczas pobierania danych');
                }
            })
            .then(data => {
                $('#Autopotion').html(data);
            })
            .catch(error => {
                console.error('Błąd:', error);
            });
    });
</script>

Source/Web Menu/Views/Home/GetAutoPotionSettings.cshtml
@model CodeInject.WebServ.Models.AutoPotionSettingsModel;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form id="AutoPotionSetting">
    <div style="display:flex">

    <div style="text-align:center">HP:</div><br />
    <input id="procHelath" name="procHelath" value="@Model.MinHelath" type="number" />
        <select class="form-select" id="hpItemIndex" name="number">
        @for (int i = 0; i < Model.ItemsList.Count; i++)
        {
                @if (i != Model.HealthItemIndex){
                    @:<option value="@i" id="@Model.ItemsList[i].Name">
                 }
                 else{
                    @:<option value="@i" id="@Model.ItemsList[i].Name" selected>
                 }
                    @Model.ItemsList[i].Name
            @:</option>
        }
    </select>
        <input id="hpItemDurr" value="@Model.HelathDurration" type="number" />
    </div>
    <br />
    <div style="display:flex">
    MP:<br />
    <input id="ManaProcentage" value="@Model.MinMana"  type="number" />
        <select class="form-select" id="MpItem" name="number">
            @for (int i = 0; i < Model.ItemsList.Count; i++)
        {       @if (i != Model.ManaItemIndex){
                    @:<option value="@i" id="@Model.ItemsList[i].Name">
                 }
                 else{
                    @:<option value="@i" id="@Model.ItemsList[i].Name" selected>
                 }
                    @Model.ItemsList[i].Name
            @:</option>
        }
        </select>       <input id="ManaPotionDurration" value="@Model.ManaDurration" type="number" />
        </div>
        <br />
    <input type="submit" id="submitButton" multiple class="form-control form-control-sm"/>
</form>


<script>
    function submitSettings() { 
       $.ajax({
          type: "POST",
          url: url,
          data: data,
          success: success,
          dataType: dataType
        });
    }
</script>

Source/Web Menu/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h1 class="display-4">Welcome</h1>
    <h2>WineBot Rose Online</h2>

</div>





<div  style="display:flex">
    
    <div style="width:40%;padding-right:15px">

        <div multiple class="form-control form-control-sm"  id="PlayerInfo" style="padding-right:15px">
        </div>

        <div multiple class="form-control form-control-sm"  id="TargetInfo" style="border-top:solid; padding-right:15px">
            </div>
    </div>
    <div multiple class="form-control form-control-sm"  id="NpcList" >
        </div>
  
</div>


<p id="p1"></p>


        <script>


   const CharacterInformationSocket = new WebSocket('ws://localhost:2458/CharacterInfo');

    CharacterInformationSocket.addEventListener('message', (event) => {
                // Przykład: Wysłanie danych JSON do kontrolera za pomocą fetch
                fetch('/Home/UserInformation?characterDataJson=' + event.data, {
                    method: 'GET',
                    headers: {
                        'Content-Type': 'application/json'
                    }
                })
                    .then(response => {
                        if (response.ok) {
                            return response.text();
                        } else {
                            throw new Error('Błąd podczas pobierania danych');
                        }
                    })
                    .then(data => {
                        $('#PlayerInfo').html(data);
                    })
                    .catch(error => {
                        console.error('Błąd:', error);
                    });
            });



    const socket = new WebSocket('ws://localhost:2458/NpcList');

    socket.addEventListener('message', (event) => {
        // Przykład: Wysłanie danych JSON do kontrolera za pomocą fetch
        fetch('/Home/NpcList?npcDataJson=' + event.data, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json'
            }
        })
            .then(response => {
                if (response.ok) {
                    return response.text();
                } else {
                    throw new Error('Błąd podczas pobierania danych');
                }
            })
            .then(data => {
                $('#NpcList').html(data);
            })
            .catch(error => {
                console.error('Błąd:', error);
            });
    });

            setInterval(refresh, 500);


    function refresh() {
        /*$.ajax({
            url: '/Home/UserInformation', // Adres kontrolera i akcji, które zwracają nową zawartość
            type: 'GET', // Typ żądania
            dataType: 'html', // Typ danych, jakie oczekujemy w odpowiedzi
            success: function (data) {
                // Aktualizacja zawartości elementu za pomocą otrzymanych danych
                $('#PlayerInfo').html(data);
            }
        });

        $.ajax({
            url: '/Home/NpcList', // Adres kontrolera i akcji, które zwracają nową zawartość
            type: 'GET', // Typ żądania
            dataType: 'html', // Typ danych, jakie oczekujemy w odpowiedzi
            success: function (data) {
                // Aktualizacja zawartości elementu za pomocą otrzymanych danych
                $('#NpcList').html(data);
            }
        });*/

        $.ajax({
            url: '/Home/TargetInfo', // Adres kontrolera i akcji, które zwracają nową zawartość
            type: 'GET', // Typ żądania
            dataType: 'html', // Typ danych, jakie oczekujemy w odpowiedzi
            success: function (data) {
                // Aktualizacja zawartości elementu za pomocą otrzymanych danych
                $('#TargetInfo').html(data);
            }
        });
    }
</script>




<!--
<script>
    var socket = new WebSocket('ws://localhost:8080/myService');

    socket.addEventListener('open', (event) => {
        console.log('Połączenie WebSocket zostało nawiązane.');
        socket.send("Connected");
    });


    function send()
    {
        socket.send("TEST");
    }

    socket.addEventListener('message', (event) => {
        console.log('Odebrano wiadomość od serwera:', event.data);
        document.getElementById("p1").innerHTML = event.data;
    });

    socket.addEventListener('close', (event) => {
        if (event.wasClean) {
            console.log('Połączenie WebSocket zostało zamknięte poprawnie.');
        } else {
            console.log('Połączenie WebSocket zostało zamknięte niepoprawnie.');
        }
        console.log('Kod zamknięcia:', event.code, 'Powód:', event.reason);
    });

    socket.addEventListener('error', (error) => {
        console.error('Wystąpił błąd połączenia:', error);
    });
</script>
-->

Source/Web Menu/Views/Home/NpcList.cshtml
@model List<CodeInject.WebServ.Models.NPCModel>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<style>
    .custom-underline {
        border-bottom: 1px solid #000; 
        display: inline-block; 
        padding-bottom: 2px; 
    }
</style>

<div class=" form-control-sm">
    @foreach (CodeInject.WebServ.Models.NPCModel t in Model)
    {
        <div >
            <div style="width:100%;" class="custom-underline actor-names">[Index] Name:<b>@t.Name</b></div><br>
             Hp: @t.Hp / @t.MaxHp<br> 
             <br>
            X: @(t.X/100)<br>
            Y: @(t.Y / 100)<br>
            Z: @(t.Z / 100)<br>
            <br>
    </div>
    }

</div>

Source/Web Menu/Views/Home/SimpleFilter.cshtml
@using CodeInject.PickupFilters;
@using CodeInject.WebServ.Models.PickUpFilter;
@using System.Collections;
@using Newtonsoft.Json;
@model SimpleFilterModel;

@{
    Hashtable ItemTypeNames = new Hashtable();


    ItemTypeNames.Add(0x08, "Weapon");
    ItemTypeNames.Add(0x09, "Shield");
    ItemTypeNames.Add(0xA, "Usable Items");
    ItemTypeNames.Add(0x02, "Hat");
    ItemTypeNames.Add(0x03, "Chest Armor");
    ItemTypeNames.Add(0x04, "Glove");
    ItemTypeNames.Add(0x05, "Shoes");
    ItemTypeNames.Add(0x0C, "Material");

    string d = Model.Filter.ToString();

    dynamic selectedList = JsonConvert.DeserializeObject<dynamic>(d);
    
}

@foreach (DictionaryEntry element in ItemTypeNames)
{
    if (selectedList.Contains((CodeInject.ItemType)element.Key))
    {
        <b><p>@element.Key</p></b>
    }else
    {
        <p>@element.Key</p>
    }
}

Source/Web Menu/Views/Home/SkillList.cshtml
@model CodeInject.WebServ.Models.PlayerSkillModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<div style="display:flex;">
    <div style="padding-right:5%">
<select id="S1" multiple class="form-control form-control-sm" style="height:90px; width:40%; min-width:400px; font-size:8pt; text-align:left;" onchange="SelectValues(this)">

    @foreach (var item in Model.UnUsedSkillList)
    {
        <option value='@item.ID'>@item.Name</option>
       
    }
        </select>
    </div><div>
    <select id="S2" multiple class="form-control form-control-sm" onclick="DeSelectValues();" style="height:90px; width:40%; min-width:400px; font-size:8pt; text-align:left;">
    @foreach (var item in Model.SkillInUseList)
    {
                <option value='@item.ID'>@item.Name</option>

    }
        </select>
    </div>
</div>
<br />
<button multiple class="form-control form-control-sm" onclick="SetSkills()">Confirm</button>

<script>



    function SetSkills() {

        var selectedValues = [...document.getElementById("S2").options].map(o => o.value);


        $.ajax({
            type: "POST",
            url: "/Home/UseSkillConfirm", 
            data: JSON.stringify(selectedValues),
            contentType: "application/json",
            dataType: "JSON",
            success: function (response) {
               
            },
            error: function () {
    
            }
        });

    }

 


    function DeSelectValues() {
        var selval = $("#S2 option:selected");
        selval[0].selected = false // deselecting
        $("#S1").append(selval);
    }

    function SelectValues(sel) {
        var selval = $("#S1 option:selected");
        selval[0].selected = false // deselecting
        $("#S2").append(selval);
    }
</script>

Source/Web Menu/Views/Home/TargetInfo.cshtml
@model CodeInject.WebServ.Models.NPCModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="info">
    <h3>Target:</h3>
    <p class="actor-names">[Index] Name: <br /><b>@Model.Name</b></p>
    <p>HP: @Model.Hp / @Model.MaxHp</p>
    <div class="progress-bar">
        <div class="progress" style="width: @Model.GetProcHP()%"></div>
    </div>
</div>

<pre class="tab1"><p>Position:  <br />X: @(Model.X / 100)</br>Y: @(Model.Y / 100)</br>Z: @(Model.Z / 100)</p></pre>

Source/Web Menu/Views/Home/UserInformation.cshtml
@model CodeInject.WebServ.Models.PlayerInfoModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

    <div class="info">
    <p class="actor-names">Name: <b>@Model.Name</b></p>
    <p>HP: @Model.Hp / @Model.MaxHp</p>
        <div class="progress-bar">
        <div class="progress" style="width: @Model.getPrecHP()%"></div>
        </div>
    </div>
    
    <div class="info">
        <p>MP: @Model.Mp / @Model.MaxMp</p>
    <div class="progress-bar">
        <div class="progress" style="background-color: blue; width: @Model.getPrecMP()%"></div>
        </div>
    </div>

<pre class="tab1"><p>Position:  <br />X: @(Model.X / 100)</br>Y: @(Model.Y / 100)</br>Z: @(Model.Z / 100)</p></pre>

<pre class="tab1">Buffs :@Model.BuffCount</pre>

Source/Web Menu/Views/Pickup/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div id="Filter">Wait...</div>

<script>

    const socket = new WebSocket('ws://localhost:2458/Filter');

    socket.addEventListener('open', function (event) {
        console.log('Połączono z serwerem WebSocket (z użyciem addEventListener)');
        socket.send("GetFilter");
    });


    socket.addEventListener('message', (event) => {
        // Przykład: Wysłanie danych JSON do kontrolera za pomocą fetch
        fetch('/Pickup/SimpleFilter', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(event.data)
        })
            .then(response => {
                if (response.ok) {
                    return response.text();
                } else {
                    throw new Error('Błąd podczas pobierania danych');
                }
            })
            .then(data => {
                $('#Filter').html(data);
            })
            .catch(error => {
                console.error('Błąd:', error);
            });
    });

</script>

Source/Web Menu/Views/Pickup/SimpleFilter.cshtml
@model CodeInject.WebServ.Models.PickUpFilter.SimpleFilterModel;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<input type="checkbox" value="Materials" @(Model.Filter.Contains(CodeInject.ItemType.Material) ? "checked" : "")>Materials</input></br>
<input type="checkbox" value="Armor" @(Model.Filter.Contains(CodeInject.ItemType.ChestArmor) ? "checked" : "")>Armors</input></br>
<input type="checkbox" value="Gloves" @(Model.Filter.Contains(CodeInject.ItemType.Gloves) ? "checked" : "")>Gloves</input></br>
<input type="checkbox" value="Hat" @(Model.Filter.Contains(CodeInject.ItemType.Hat) ? "checked" : "")>Hats</input></br>
<input type="checkbox" value="Shoes" @(Model.Filter.Contains(CodeInject.ItemType.Shoes) ? "checked" : "")>Shoes</input></br>
<input type="checkbox" value="Consume" @(Model.Filter.Contains(CodeInject.ItemType.UsableItem) ? "checked" : "")>Consumables</input></br>
<input type="checkbox" value="Weapons" @(Model.Filter.Contains(CodeInject.ItemType.Weapon) ? "checked" : "")>Weapons</input></br>
<input type="checkbox" value="Shields" @(Model.Filter.Contains(CodeInject.ItemType.Shield) ? "checked" : "")>Shields</input></br>

Source/Web Menu/Views/PlayerInfo/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@ViewBag.ReceivedMessage

Source/Web Menu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bot_Menu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bot_Menu.styles.css" asp-append-version="true" />

     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
     <script src="https://unpkg.com/htmx.org@1.9.5"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bot_Menu</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AutoPotion">AutoPotion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Skill" asp-action="Index">SkillList</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pickup" asp-action="Index">Pickup filter</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <style>
        .progress-bar {
            width: 100%;
            height: 20px;
            background-color: #f2f2f2;
            border-radius: 5px;
            margin-bottom: 10px;
        }

        .progress {
            height: 100%;
            background-color: red;
            border-radius: 5px;
        }

        .info {
            margin-bottom: 10px;
        }
    </style>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Bot_Menu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Source/Web Menu/Views/Skill/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div id="SkillList">
    Wait....
</div>

<script>
    const socket = new WebSocket('ws://localhost:2458/SkillList');

    socket.addEventListener('open', function (event) {
        console.log('Połączono z serwerem WebSocket (z użyciem addEventListener)');
        socket.send("GetSkills");
    });


    socket.addEventListener('message', (event) => {
        // Przykład: Wysłanie danych JSON do kontrolera za pomocą fetch
        fetch('/Skill/SkillList', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(event.data)
        })
            .then(response => {
                if (response.ok) {
                    return response.text();
                } else {
                    throw new Error('Błąd podczas pobierania danych');
                }
            })
            .then(data => {
                $('#SkillList').html(data);
            })
            .catch(error => {
                console.error('Błąd:', error);
            });
    });

</script>

Source/Web Menu/Views/Skill/SkillConfirm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Source/Web Menu/Views/Skill/SkillList.cshtml
@model CodeInject.WebServ.Models.PlayerSkillModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div id="SkillList">
 @if (Model != null)
{
    <div id="SkillList"  style="display:flex;">

        <div style="padding-right:5%">
            <select id="S1" multiple class="form-control form-control-sm" style="height:90px; width:40%; min-width:400px; font-size:8pt; text-align:left;" onchange="SelectValues(this)">


                @foreach (var item in Model.UnUsedSkillList)
                {
                    <option value='@item.ID'>@item.Name</option>

                }
            </select>
        </div><div>
            <select id="S2" multiple class="form-control form-control-sm" onclick="DeSelectValues();" style="height:90px; width:40%; min-width:400px; font-size:8pt; text-align:left;">
                @foreach (var item in Model.SkillInUseList)
                {
                    <option value='@item.ID'>@item.Name</option>

            }
            </select>
        </div>

    </div>

<br />
<button multiple class="form-control form-control-sm" onclick="SetSkills()">Confirm</button>
}
</div>

<script>

    function SetSkills() {

        var selectedValues = [...document.getElementById("S2").options].map(o => o.value);

        $.ajax({
            type: "POST",
            url: "/Skill/SkillConfirm",
            data: JSON.stringify(selectedValues),
            contentType: "application/json",
            dataType: "JSON",
            success: function (response) {
            },
            error: function () {
            }
        });

    }

 


    function DeSelectValues() {
        var selval = $("#S2 option:selected");
        selval[0].selected = false // deselecting
        $("#S1").append(selval);
    }

    function SelectValues(sel) {
        var selval = $("#S1 option:selected");
        selval[0].selected = false // deselecting
        $("#S2").append(selval);
    }
</script>